# Site settings
title: "Dual State Economic Theory"
subtitle: "A New Lens for Understanding Value and Trust"
author: "Joseph Patrick Mooney"
description: "A new lens for examining how value moves between potential states (measurement systems, stored trust) and kinetic states (active exchange, realized utility) across economic systems."

# GitHub Pages settings
url: "https://joemooney.github.io"
baseurl: "/dual-state-value-theory"

# Theme selection - using minima for clean academic look
theme: minima

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Collections for chapters
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

# Navigation structure
header_pages:
  - abstract.md
  - index.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Academic features
scholar:
  style: apa
  
# Google Analytics (optional)
# google_analytics: YOUR_GA_ID

# Social media
github_username: joemooney

# Exclude files from build
exclude:
  - dialog.txt
  - CLAUDE.md
  - README.md
  - .gitignore